"""initial_schema

Revision ID: bb9db453bbb6
Revises: 
Create Date: 2026-09-01 11:29:04.479200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb9db453bbb6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_number', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('monthly_rent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_unit_number'), ['unit_number'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('dismissed_rent_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('month_covered', sa.String(length=7), nullable=False),
    sa.Column('dismissed_by_id', sa.Integer(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dismissed_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'month_covered', name='uq_dismissed_alert_unit_month')
    )
    with op.batch_alter_table('dismissed_rent_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dismissed_rent_alerts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dismissed_rent_alerts_month_covered'), ['month_covered'], unique=False)
        batch_op.create_index(batch_op.f('ix_dismissed_rent_alerts_unit_id'), ['unit_id'], unique=False)

    op.create_table('maintenance_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_requests_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_requests_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_requests_unit_id'), ['unit_id'], unique=False)

    op.create_table('rent_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('month_covered', sa.String(length=7), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rent_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rent_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rent_payments_month_covered'), ['month_covered'], unique=False)
        batch_op.create_index(batch_op.f('ix_rent_payments_unit_id'), ['unit_id'], unique=False)

    op.create_table('maintenance_request_contractors',
    sa.Column('maintenance_request_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['maintenance_request_id'], ['maintenance_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('maintenance_request_id', 'contractor_id')
    )
    op.create_table('maintenance_timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_request_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['maintenance_request_id'], ['maintenance_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_timeline_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_timeline_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_timeline_events_maintenance_request_id'), ['maintenance_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_timeline_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_timeline_events_maintenance_request_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_timeline_events_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_timeline_events_actor_id'))

    op.drop_table('maintenance_timeline_events')
    op.drop_table('maintenance_request_contractors')
    with op.batch_alter_table('rent_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rent_payments_unit_id'))
        batch_op.drop_index(batch_op.f('ix_rent_payments_month_covered'))
        batch_op.drop_index(batch_op.f('ix_rent_payments_id'))

    op.drop_table('rent_payments')
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_requests_unit_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_requests_status'))
        batch_op.drop_index(batch_op.f('ix_maintenance_requests_priority'))
        batch_op.drop_index(batch_op.f('ix_maintenance_requests_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_requests_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_requests_created_at'))

    op.drop_table('maintenance_requests')
    with op.batch_alter_table('dismissed_rent_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dismissed_rent_alerts_unit_id'))
        batch_op.drop_index(batch_op.f('ix_dismissed_rent_alerts_month_covered'))
        batch_op.drop_index(batch_op.f('ix_dismissed_rent_alerts_id'))

    op.drop_table('dismissed_rent_alerts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_unit_number'))
        batch_op.drop_index(batch_op.f('ix_units_id'))
        batch_op.drop_index(batch_op.f('ix_units_archived'))

    op.drop_table('units')
    # ### end Alembic commands ###
